# 로컬 개발환경 설정 (H2 Database)
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:duit;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
    duit: DEBUG

# JWT 개발용 설정
jwt:
  secret: localDevelopmentSecretKeyForTestingOnly12345
  access-token-validity: 86400000 # 24시간
