global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'duit-server'
    static_configs:
      - targets: ['duit-server-prod:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['duit-redis-prod:9121']
    scrape_interval: 15s

  - job_name: 'mysql'
    static_configs:
      - targets: ['duit-mysql-prod:9104']
    scrape_interval: 15s