name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: 테스트 실행
    uses: ./.github/workflows/test.yml
    with:
      upload-artifacts: true
    secrets: inherit

  upload-test-results:
    name: 테스트 결과 업로드
    needs: test
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
    
    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-results-${{ github.run_id }}
          path: test-results/

      - name: Upload test results as Pages artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: test-report-${{ github.run_id }}
          path: test-results/